# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# discover Azure inventory
---
- name: JUMPHOST OVERLAY | setting key_path
  set_fact: key_path="{{ key_path | default(playbook_dir) }}"

- include_tasks: discover-resourcegroup.yml

- name: JUMPHOST AZURE | discovering {{ application }}
  azure_rm_publicipaddress_facts:
    resource_group: "{{ specified_resourcegroup.name }}"
    name: "{{ project }}_{{ application }}_{{ ec2_tag_Role | default('none') }}_{{ cluster | default('none') }}_{{ dataflow | default('none') }}_{{ item }}_external_ip"
  with_sequence: count={{ count }}
  register: found_jumphosts

- name: JUMPHOST OVERLAY | adding all jumphosts to {{ application }} host group
  add_host: hostname="{{ item.ansible_facts.azure_publicipaddresses.0.properties.ipAddress }}" groupname="{{ application }}" ansible_user="{{ user }}" ansible_ssh_private_key_file="{{ key_path }}/{{cloud }}-{{ region }}-{{ project }}-{{ application }}-{{ domain }}-private-key.pem"
  when: item.ansible_facts.azure_publicipaddresses | length > 0
  with_items: "{{ found_jumphosts.results }}"
