# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# OS tasks that occur post-boot and pre-appplication installation
---
# in a jumphost, eth1 is always private internal
- set_fact:
    private_internal_interface: eth1
  when:
    - internal_subnet is defined

- block:
  
  - name: JUMPHOST PREFLIGHT OVERLAY | creating ifcfg-{{ private_internal_interface }}
    blockinfile:
      path: "/etc/sysconfig/network-scripts/ifcfg-{{ private_internal_interface }}"
      create: yes
      mode: 0644
      block: |
        BOOTPROTO=dhcp
        DEVICE={{ private_internal_interface }}
        ONBOOT=yes
        TYPE=Ethernet
        USERCTL=no
        DEFROUTE=no
    when:
      - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      - private_internal_interface is defined
  
  - block:
    
    - name: JUMPHOST PREFLIGHT OVERLAY | restart networking with systemd
      systemd: name=network state=restarted
      when:
        - ansible_distribution_version is version_compare('7', '>=')
  
    - name: JUMPHOST PREFLIGHT OVERLAY | restart networking with sysvinit
      sysvinit: name=network state=restarted
      when:
        - ansible_distribution_version is version_compare('7', '<')
    
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
  become: yes
  when: cloud == 'aws' or cloud == 'osp'
   
- name: JUMPHOST PREFLIGHT OVERLAY | ensure sshd_config is writable
  command: chattr -i /etc/ssh/sshd_config
  become: yes

- block:
  
  - name: JUMPHOST PREFLIGHT OVERLAY | ensuring sshd listens on provisioning network
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^#ListenAddress 0.0.0.0"
      backrefs: yes
      line: "ListenAddress {{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"

  - name: JUMPHOST PREFLIGHT OVERLAY | configuring public key authentication only
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^#PubkeyAuthentication yes"
      backrefs: yes
      line: "PubkeyAuthentication yes"

  - name: JUMPHOST PREFLIGHT OVERLAY | limiting login attempts
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^#MaxAuthTries 6"
      backrefs: yes
      line: "MaxAuthTries 3"
  
  - name: JUMPHOST PREFLIGHT OVERLAY | restarting sshd with systemd
    systemd: name=sshd state=restarted daemon_reload=yes
    when:
      - ansible_distribution_version is version_compare('7', '>=')
  
  - name: JUMPHOST PREFLIGHT OVERLAY | restarting sshd with sysvinit
    sysvinit: name=sshd state=restarted
    when:
      - ansible_distribution_version is version_compare('7', '<')
      
  become: yes
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: JUMPHOST PREFLIGHT OVERLAY | generating UUID
  shell: /usr/bin/uuidgen | /usr/bin/tr -d \-
  register: uuid

# the lineinfile plays aren't intended to be idempotent
- block:
  
  - name: CORE POSTFLIGHT | checking for /usr/bin/hostnamectl
    stat: path=/usr/bin/hostnamectl
    register: existing_file
  
  - block:
    
    - name: JUMPHOST PREFLIGHT OVERLAY | setting hostname actively so rebooting is unnecessary
      command: /usr/bin/hostnamectl set-hostname {{ application }}-{{ uuid.stdout }}
      
    - name: JUMPHOST PREFLIGHT OVERLAY | setting hostname actively so rebooting is unnecessary
      command: /usr/bin/hostnamectl --pretty set-hostname "{{ tenant }} {{ application }}"
      
    when: existing_file.stat.exists
  
  - name: CORE POSTFLIGHT | checking for /etc/hostname
    stat: path=/etc/hostname
    register: existing_file
      
  - name: JUMPHOST PREFLIGHT OVERLAY | setting hostname in /etc/hostname
    replace:
      path: /etc/hostname
      regexp: "{{ hostvars[inventory_hostname].ansible_hostname }}.ec2.internal"
      replace: "{{ application }}-{{ uuid.stdout }}.localdomain"
    when: existing_file.stat.exists
    
  - name: JUMPHOST PREFLIGHT OVERLAY | setting {{ application }}-{{ uuid.stdout }}.localdomain in /etc/sysconfig/network
    lineinfile:
      dest: /etc/sysconfig/network
      state: present
      insertafter: EOF
      line: "HOSTNAME={{ application }}-{{ uuid.stdout }}.localdomain"

  - name: JUMPHOST PREFLIGHT OVERLAY | setting {{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }} to {{ application }}-{{ uuid.stdout }}.localdomain in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      insertafter: EOF
      # regexp: "^127.0.0.1  localhost localhost.localdomain localhost4 localhost4.localdomain4"
      # backrefs: yes
      # line: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 {{ hostvars[inventory_hostname].ansible_hostname }}"
      line: "{{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}    {{ application }}-{{ uuid.stdout }}.localdomain {{ application }}-{{ uuid.stdout }} {{ application }}"

  - name: JUMPHOST PREFLIGHT OVERLAY | ensuring hostname changes persist after reboot
    lineinfile:
      dest: /etc/cloud/cloud.cfg
      state: present
      insertafter: EOF
      line: 'preserve_hostname: true'
    when:
      - cloud == 'aws'
      
  become: yes
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

# community CentOS AMI ships with postfix enabled so we need to disable it
# adding the failed_when makes it idempotent
- name: JUMPHOST PREFLIGHT OVERLAY | stopping postfix
  service:
    name: postfix
    state: stopped
  become: yes
  failed_when: no
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' 
  
# annnnd remove it
- name: JUMPHOST PREFLIGHT OVERLAY | removing postfix
  package:
    name: postfix
    state: absent
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    
# community CentOS image ships with rpcbind enabled; we don't use NFS by default so disable it
- name: JUMPHOST PREFLIGHT OVERLAY | stopping rpcbind
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  become: yes
  with_items:
    - rpcbind
    - rpcbind.socket
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - cloud == 'azure'